### ISSUE TITLE
Ionic Native onItemPressed() not working

### ISSUE THREAD

**Issue by felixbroehl** [johanblomgren/cordova-plugin-indexappcontent#23]
It would be great if somebody can look at this: https://github.com/ionic-team/ionic-native/issues/2255

**Comment by felixbroehl** [comment]
@NiklasMerz

**Comment by NiklasMerz** [comment]
@felixbroehl I hope I can help you.

**Comment by felixbroehl** [comment]
@NiklasMerz @iihadeed I did some research and [cordova-plugin-indexappcontent/www/IndexAppContent.js](https://github.com/johanblomgren/cordova-plugin-indexappcontent/blob/master/www/IndexAppContent.js) containing all other Methods but not the onItemPressed-Method. Can this be the cause why my code is logging `WARN: Native: tried calling IndexAppContent.onItemPressed, but the IndexAppContent plugin is not installed` ?

**Comment by NiklasMerz** [comment]
Yes that is correct.  You have to attach the `onItemPressed` to the `IndexAppContent` yourself. This plugin is designed to use your function as a callback. If you have problems with Ionic Native, you should try using the plugin the standard way to test if the plugin is installed correctly.

**Comment by MarcoEidinger** [comment]
As per plugin implementation:

> If user taps on a search result in spotlight then the app will be launched. You can register a Javascript handler to get informed when this happens. Assign a handler function to window.plugins.indexAppContent.onItemPressed that takes the payload as argument

If you have not yet assigned a named function **onItemPressed** yet then you can't use ionic notation

`this.platform.ready().then(() => {
  this.indexAppContent.onItemPressed().subscribe(() => {
    console.log('called when a item is pressed');
  });
});`

But I cannot say if that's the only reason you see log message `WARN: Native: tried calling IndexAppContent.onItemPressed, but the IndexAppContent plugin is not installed`

There might be other issues with the way you use the plugin. @NiklasMerz is commenting actively on ionic-team/ionic-native#2255 and no issue was found in plugin code, therefore I will close this thread.

**Comment by nicolasborn** [comment]
hi marco
could you post an example how to assign the function onitempressed? i tried id but it didn't work.
