### ISSUE TITLE
Error callback : Will not update index

### ISSUE THREAD

**Issue by madansingh18** [johanblomgren/cordova-plugin-indexappcontent#5]
HI Johanblomgren,

I am trying to run the demo code in ionic platform (Using as cordova 6.1.1). But i am getting error callback as “Will not update index”. What could be cause of this issue?

var items = [{
                domain: 'com.dev.tes',
                identifier: 'TESID091',
                title: 'Test',
                description: 'Test',
                keywords: ['Test'],
                url: 'http://pk.se/images/logo_dark.png',
            }];
            window.plugins.indexAppContent.init();
            window.plugins.indexAppContent.setItems(items, function() {
                alert('Successfully set items');
            }, function(error) {
                alert('Error: ' + error);
            });
            });

Tested on the device.

Thanks,
Madan

**Comment by johanblomgren** [comment]
Hi there Madan,

The error callback you are seeing would be called when `- (BOOL)_shouldUpdateIndex` evaluate to false, i.e. when you try to re-index content within the set indexing interval (which by default is arbitrarily set to 24h). You can change this interval to 1 minute by calling `window.plugins.indexAppContent.setIndexingInterval(1, function() {
        console.log('Successfully set interval');
    }, function(error) {
        // Handle error
    });`

If this does not resolve it for you, there might be some bug related to checking dates that is causing issues.

**Comment by madansingh18** [comment]
Thanks, 
After putting setIndexingInterval; I am getting success callback "Successfully set interval". But its still not showing in "spotlight search". Do i need to reset item?

**Comment by johanblomgren** [comment]
Do you get the success callback when calling `window.plugins.indexAppContent.setItems`?

Clearing items should not be necessary - they will be overwritten (if they have the same identifiers).

**Comment by johanblomgren** [comment]
@madansingh18 Did you manage to get it working?

**Comment by madansingh18** [comment]
Sorry for delayed response...Yes i manage to get it working...But i am not able to setItems dynamically while accessing the app. After subsequent set items its start giving "Will not update index". Though i am looking into this issue and will let you know if i need any help...Thanks
