### ISSUE TITLE
can't reindex items

### ISSUE THREAD

**Issue by hessius** [johanblomgren/cordova-plugin-indexappcontent#8]
If for some reason the indexing fails (happened to me in simulator (slightly on purpose, though not sure completely how)) I am not able to reindex items.
Running the clear items method is successful, then rerunning the setItems method just gives me "Will not update index. Last update: 2016-09-07 13:51:48 +0000" which is (I'm guessing) due to the new scan being within the last scanning interval. But changing the interval and rerunning the setItems method produces the same result.
Am I missing something here or is there a bug lurking here?

**Comment by hessius** [comment]
A workaround (posted for anyone else coming across this issue)
Instead of calling setItems on app startup and then letting the plugin figure out if the interval has run out or not I'm storing the last scan date in localstorage and comparing it to the current date (in ms from 1970) and configuring the range there, and only if it is out of range will a new setItem be run. The interval meanwhile is set to 1 to allow a new indexing whenever we want, e.g. on a button press.

**Comment by johanblomgren** [comment]
@hessius Most likely a bug or some logical mistake - will have a look. For the time being, your suggestion will work (i.e. set indexing interval to 1 and manage index invalidation in your application code).
